---
title: "Lab 8 - Linear Regression in R"
author: "Madeline Berger"
date: "11/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

salmon_simple <- read_csv("salmon_simple_mb.csv")

salmon_simple

```


1. Explore the Data 

```{r}
salmon_scatter <- ggplot(salmon_simple, aes(x = year, y = imports_fresh))+
  geom_point()

salmon_scatter

#Overall, the data looks linear. Towards the end of the series there is some variation that is somewhat concerning, but for all intensive purposes it appears linear
```


2. Perform a linear regression

```{r}

salmon_model <- lm(imports_fresh ~ year, data = salmon_simple)
salmon_model
summary(salmon_model)

#equation: imports(tons) = -1498000 + 7550(Year)
#The slope means that salmon imports increase 7550 tons per year in our model. The Y intercept shows what the imports would be if we used this model to trace all th way back to year zero. It is concerning because that is extrapolating present day data to a time when this data did not exist to build a model. 


```


3. Model Diagnostics 
```{r}
plot(salmon_model)

#based on the qq plot, these residuals do appear normally distributed, there are 2 or three outliers. the residuals vs fitted graph suggests a vague pattern over time, but not enough to be conerning. 

#to view all four diagnostic plots at once and see them in the knitted document: 
par(mfrow = c(2,2))
plot(salmon_model)

```

5. Explore model fit and significance

```{r}
#Does year significantly predict salmon imports? Yes, the p-value for the model fit is small
#What does the R 2 value mean? 95% of the variance in imports can be attributed to year
#Proportion not explained by year: 5%

```


6. Prepare a final graph 
```{r}

salmon_final_graph <- ggplot(salmon_simple, aes(x = year, y = imports_fresh)) +
  geom_point()+
  geom_smooth(method = lm, se = TRUE, size = 0.5, color = "gray20") +
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(1990, 2017)) +
  labs(x = "Year", y = "U.S. Annual Fresh Salmon Imports \n(1,000 pounds)")

salmon_final_graph


```


7. Make predictions using the model 
```{r}
#create a new df with years you want to predict
new_years <- salmon_simple(year = c(2022,2024,2026,2028))
new_years

#feed that into the model 
future_predict <- predict(salmon_model, newdata = new_years, interval = "confidence")
future_predict

#bind outcomes with new_years df to create a useful table 
predictions <- data.frame(new_years, future_predict)
predictions
```


8. Find Pearson's R (correlation)
```{r}
#if you are trying to explore the correlation between variable 1 and variable 2, use: 


```

